import json
import re

desk_orig = json.loads(open("missing_desk.json", encoding="utf-8").read())
desk_trans = json.loads(open("translated_desk.json", encoding="utf-8").read())

ICU_RE = re.compile(r"\{[^{}]+,\s*(?:plural|select|selectordinal)\s*,[^{}]+\}")

# 对 ICU 复杂表达式，人工专业本地化
desk_icu_fixes = {
    "+3KiTtWq89": "移除“{folderName}”并停止 {count, plural, one {# 个远程会话} other {# 个远程会话}}？",
    "0Cs12/GF/H": "{skipped, plural, one {已跳过 # 个选定文件夹。} other {已跳过 # 个选定文件夹。}}",
    "9IxjUqgX9u": "{action, select, connect {连接连接器} disconnect {断开连接器} apply {检查配置} other {确认}}",
    "FrOZ8asmaz": "取消固定“{folderName}”并停止 {count, plural, one {# 个远程会话} other {# 个远程会话}}？",
    "HnLk2BuP0l": "在此计算机上找到 {count, plural, one {# 个 Claude Code 会话} other {# 个 Claude Code 会话}}未包含在你的会话列表中。这包括此应用列表中缺失的代码标签页会话以及从终端启动的会话。导入的会话会保留其对话记录及上次运行的权限模式，但归档状态和权限授权无法恢复。",
    "NQ97Bry/Vi": "为保持在文件夹限制内，“{name}”将不再列出，其 {count, plural, one {# 个远程会话} other {# 个远程会话}}也将停止。",
    "V1LCXkUdgY": "{others, plural, one {# 个文件夹因位于受保护位置而被跳过。} other {# 个文件夹因位于受保护位置而被跳过。}}",
    "YCJVyeVeAf": "关闭远程控制并停止 {count, plural, one {# 个远程会话} other {# 个远程会话}}？",
    "hDwD9Rb60X": "在 Claude 中打开 {count, plural, one {# 个文件} other {# 个文件}}？",
    "hOgUlX8L2M": "另一个应用想要在 Claude 中打开 {count, plural, one {# 个文件} other {# 个文件}}",
    "kI0IZ4u/6i": "停止 {count, plural, one {# 个远程会话} other {# 个远程会话}}？",
    "+bUHNDYGdG": "前往",
    "+WkyrCbxoZ": "搜索…",
    "0aHdFu/l3q": "新聊天",
    "0aNzENRakz": "安装扩展…",
    "1gIM3YS53H": "其他…",
    "8DnvhbQPVP": "在此处新建 Claude Code 会话",
    "BgxtQ/oVxb": "新建 Claude Code 会话",
    "EsGXoSX1vh": "新建代码会话",
    "oQrNKDv+Cp": "新建会话",
    "tyiWynSRix": "新建任务",
    "hPVHFt5f9s": "新聊天",
    "qHPWFPPXPZ": "设置",
    "9hQ0g4fJrV": "退出",
    "SVZWXIjLFR": "退出",
    "wWOCfDmhVO": "退出",
    "DtyTDDRpAd": "缩放",
    "9Dz1HnObV+": "全屏",
    "IfXDFsQVBx": "进入全屏",
    "RnpPCIL+MA": "退出全屏",
    "Bp0HK3PGIK": "侧边栏",
    "DNLB2o9FoA": "隐藏侧边栏",
    "i07Vmzxp/Q": "显示侧边栏",
    "yq/0RW4fkP": "终端",
    "98WeOhhkzv": "隐藏终端",
    "wBOWq9/ltQ": "显示终端",
    "WjKYiN7xRK": "文件",
    "VOEK8KwjgD": "隐藏文件",
    "RS2IDFpEs2": "显示文件",
    "ajVha5bDMT": "浏览器",
    "dpcjrIOyI3": "隐藏浏览器",
    "izpqAIME9m": "显示浏览器",
    "PvCdGhgXHO": "预览",
    "ESzemi0CIV": "隐藏预览",
    "Qzxl43PKd4": "显示预览",
    "WNFNIXqDwo": "侧边聊天",
    "GeYdDBn7CI": "隐藏侧边聊天",
    "lD3kgtcDmI": "显示侧边聊天",
    "TRLngw1jo9": "更改",
    "1+JBMXlHXX": "隐藏更改",
    "1MVONmjI+o": "显示更改",
    "S9rMbKFol0": "任务",
    "lba/DHLeeP": "关闭任务",
    "+CCvoj7koS": "下一个任务",
    "MPdc7dzZqC": "上一个任务",
    "aMz0CHEoCu": "关闭聊天",
    "R6IJaQd5ea": "上一个聊天",
    "Ubrd2osCEK": "下一个聊天",
    "xdFFXdcjAb": "关闭会话",
    "bzMD3ZDNrw": "上一个会话",
    "ibf3kUb02G": "下一个会话",
    "jB0vgfRwm1": "最近会话",
    "Ri9DuYmnrF": "继续上次 Claude Code 会话",
    "t77UbkPnXg": "重新打开已关闭的会话",
    "xjOwyIuGQi": "分屏视图",
    "p/l1lka4F6": "关闭分屏视图",
    "bRbh5As7Cl": "关闭窗格",
    "xhaQ8bIWLL": "在右侧新建会话",
    "GpaIIAZ6mn": "在下方新建会话",
    "U//bQDu9Yk": "在新窗口中新建会话",
    "CtFSeJn07M": "向左移动分屏视图",
    "CWan0niJEF": "向右移动分屏视图",
    "lvuLNhxpRk": "向上移动分屏视图",
    "9xlOteKqqc": "向下移动分屏视图",
    "v8OB1P67un": "聚焦上一个分屏视图",
    "tNl/pVLl8O": "聚焦下一个分屏视图",
    "CJjRo3EXGm": "粘贴并匹配样式",
    "SH7/9kzZqB": "查找",
    "qc5Ud3Dmgi": "查找…",
    "ecEY91WxUG": "在文件中查找…",
    "vk8ax2mb3h": "命令面板…",
    "tjzoYuBJHm": "重新加载",
    "eLz9p/jzYR": "最小化",
    "2XrQNpFdQa": "隐藏其他",
    "2pmRZmlzKv": "显示全部",
    "DSquCL0ADp": "前置全部窗口",
    "m3wVzL5scw": "服务",
    "Cdtw/vFJBa": "打开文件夹…",
    "ryiKMjMBiA": "打开文件…",
    "H37kTzMmG0": "安装未打包的扩展…",
    "+aT0D9mFR4": "打开扩展文件夹",
    "mE6I0f4vu4": "打开扩展设置文件夹",
    "ewJhC1J2qh": "打开 MCP 日志文件",
    "M+KRNXNx21": "打开开发者配置文件",
    "PqLmxu2Ja/": "打开应用配置文件",
    "MirrBa7PT4": "在文件资源管理器中显示日志",
    "lxTsiR6Otz": "在文件资源管理器中显示 Cowork 会话数据",
    "jRIM96o2KQ": "显示日志",
    "ZbUyEshj8d": "正在检查更新…",
    "MJmh44uBMj": "键盘快捷键",
    "hZ45Tnwwfh": "询问 Claude",
    "hJ/ql9DFRu": "打开",
    "8Fl1Xq7Kht": "远程控制",
    "w0rIv0wdPR": "登录到 GitHub",
}

for k, v in desk_icu_fixes.items():
    desk_trans[k] = v

open("translated_desk_cleaned.json", "w", encoding="utf-8").write(
    json.dumps(desk_trans, ensure_ascii=False, indent=2)
)
print("Saved translated_desk_cleaned.json with", len(desk_trans), "items")
